### PR TITLE
Jakarta

### PR DESCRIPTION
**Pull request by weberjn**
With this PR, the wiki comes up and works under Tomcat 10. The AttachmentServlet uses Fileupload 2 now.
I haven't ported any tests, skipped all tests, built with 'mvn -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Denforcer.skip=true'

Update: most unit tests work now, see comment in
https://issues.apache.org/jira/browse/JSPWIKI-1170

### CODE REVIEW

**Review by spyhunter99 — COMMENTED** [review]
aside from some formatting related issues in the pom's. changes look reasonable to me. i also just migrated a huge project to jdk17 with jakarata. appreciate the work.

i did run into a compile issue, actually it's dependency resolution. Here's the output:

Could not resolve dependencies for project org.apache.jspwiki:jspwiki-util:jar:3.0.0-SNAPSHOT: net.sourceforge.stripes:stripes:jar:1.6.0-JakartaEE10 was not found in https://repo.maven.apache.org/maven2 during a previous attempt

**Comment by weberjn** [comment]
Yes, the needed stripes version is not in central. So I built it locally.
See my comment in JSPWIKI-1170.
Someone might ask stripes to publish to central.

A harder problem still is  xmlrpc-2.0.1.jar containing  org.xml.sax.

I'd suggest to replace the xmlrpc stuff with a REST based implementation.
Unfortunately, Jersey is quite large, so this shouldn't be in the wiki by
default.

Juergen

Am Di., 15. Okt. 2024 um 03:05 Uhr schrieb spyhunter99 <
***@***.***>:

**Comment by spyhunter99** [comment]
> xmlrpc

wow i haven't seen a problem with xmlrpc in at least 15 years. I'm a CXF fan (as much as i hate it) but it's generally the better choice. Apache projects also tend to use apache projects for stuff. makes sense. i might branch of your branch and see what i can do.

**Comment by spyhunter99** [comment]
ok so after reviewing the jsp wiki code, stripes seems like it is a test dependency only, maybe there's an alternative we can use

**Comment by juanpablo-santos** [comment]
Hi,

I'd like to work on this issue; as for the Stripes dependency, I think it's better in the long term if we replace it with Mockito. TestEngine would seem to me the biggest pain, but I think some preconfigured mocks would do the trick. At least I want to give this a try. 

As for xmlrpc, I don't have an opinion yet, we've always tried to come up with "bare-jdk" solutions in order to not bloat the jspwiki-war with a lot of dependencies and to reduce the amount of things to learn to work with JSPWiki, but if working with CXF (or whatever we choose) simplifies thing I wouldn't oppose to that either.

**Comment by weberjn** [comment]
As for xmlrpc: I once had to get a JEE resource adapter's jars in the .rar onto the classpath of a project: in maven validate got the dependency, unpacked it and added the jars as systemPath dependency to the project. Not pretty, but works.
We could do the same with xmlrpc: unjar, delete org.xml.sax, jar again .. maven-antrun-plugin can do things.

**Comment by spyhunter99** [comment]
i'm also attempting mocks for the servlet specific bits but don't have a huge amount of time into it. Does any one know ...how..the xmlrpc library is used? i.e. if we just remove the feature set that depends on xmlrpc, what would break?

**Comment by weberjn** [comment]
xmlrpc is used for the weblog api : https://en.wikipedia.org/wiki/MetaWeblog

in [MetaWeblogHandler.java](https://github.com/apache/jspwiki/blob/master/jspwiki-main/src/main/java/org/apache/wiki/xmlrpc/MetaWeblogHandler.java)

I doubt that anybody uses it anymore. And I believe it is broken bei [CsrfProtectionFilter.java](https://github.com/apache/jspwiki/blob/master/jspwiki-http/src/main/java/org/apache/wiki/http/filter/CsrfProtectionFilter.java) anyway.

Still, it is a useful functionality, but it should be implemented in REST.

**Comment by spyhunter99** [comment]
just my opinion, but i say ditch the xmlrpc dependency and build a new solution with the equivalent functionality but with newer tech. It looks like the current functionality, exposing capability for a web blog from a wiki doesn't seem like a good fit.

IMO, what's really needed is basic crud apis that are accessible via rest api. i wouldn't mind working that aspect but if there isn't a clear need for it at the moment, but we can probably make due without either

**Comment by juanpablo-santos** [comment]
Hi! didn't have a lot of time this past few weeks, but I've managed to open https://github.com/weberjn/jspwiki/pull/1 to remove Stripes and, while at it, also Jetty

I'd like to look at what can be done with the xmlrpc usage. Given that xmlrpc is not ported to jakarta, perhaps ditching it would be an alternative, providing something equivalent after landing the jakarta branch. A 5 minute google search seems to imply that metaweblog has been superseeded by micropub so that might be an option. Providing a full rest api would be nicer, but I see that unrelated to the move to jakarta, could be tackled afterwards (and given our current pace I wouldn't expect to be delivered shortly)

@weberjn would you mind looking at the above PR? Also, I'm going to open a jakarta branch, so that this PR can be merged there. I would like to push a few PRs into master and merge them on this new branch before merging, but I'd prefer to go with this first to keep it as manageable as possible.

**Comment by juanpablo-santos** [comment]
ouch, opened the jakarta branch, but I've noticed this PR cannot be merged now due to conflicts, @weberjn would you mind looking at that too? and of course, a thousand thanks for all the work that has gone into this PR! :-)

**Pull request merged**
